import ConfigureAmplifyClientSide from '@/components/ConfigureAmplifyClientSide';
import '@/styles/globals.css';
import { withAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import type { AppProps } from 'next/app';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <ConfigureAmplifyClientSide />
      <Component {...pageProps} />
    </>
  );
}

export default withAuthenticator(App);
